MyVers: inc/fileHandler.h File Reference
fileHandler.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <stdbool.h>
#include "helpers.h"
#include "list.h"
Functions
bool copyFilesToSnapshotTemp (int argc, const char *argv[])
void copyFile (const char *fromPath, const char *destinyPath)
void copyFilesTo (const char **files, int length, const char *path)
void copyFilesToTemp (const char **files, int length)
void copyFilesToWorkspace (const char **files, int length, const char *path)
void moveFilesTo (const char *from, const char *to)
void moveFilesToTemp (const char *from)
void addTextInTxtFile (const char *path, const char *text)
void addSnapshotTextInLog (const char *snapshotName, const char *hash)
void addSnapshotTempFilesInList (FileList *list)
void addFilesIntoSnapshotFolder (FileList *list, const char *hash)
void addFilesToDir (FileList *list)
void addTempFilesIntoList (FileList *list)
Function Documentation
addFilesIntoSnapshotFolder()
void addFilesIntoSnapshotFolder (FileList * list, const char * hash)
References createFilesInSnapshotFolder(), print(), and verifyDirectory().
Referenced by createSnapshot().
addFilesToDir()
void addFilesToDir (FileList * list)
References createFilesInSnapshotFolder(), print(), and verifyDirectory().
Referenced by getTempFiles().
addSnapshotTempFilesInList()
void addSnapshotTempFilesInList (FileList * list)
References addFilesToList(), and getFilesInDirectory().
Referenced by createSnapshot().
addSnapshotTextInLog()
void addSnapshotTextInLog (const char * snapshotName, const char * hash)
References addTextInTxtFile().
Referenced by createSnapshot().
addTempFilesIntoList()
void addTempFilesIntoList (FileList * list)
References addFilesToList(), getFilesInDirectory(), and print().
Referenced by getTempFiles().
addTextInTxtFile()
void addTextInTxtFile (const char * path, const char * text)
References print(), and verifyFile().
Referenced by addSnapshotTextInLog(), and createLogFolder().
copyFile()
void copyFile (const char * fromPath, const char * destinyPath)
References print(), and verifyFile().
Referenced by copyFilesTo(), copyFilesToSnapshotTemp(), copyFilesToTemp(), and copyFilesToWorkspace().
copyFilesTo()
void copyFilesTo (const char ** files, int length, const char * path)
References copyFile().
Referenced by moveFilesTo().
copyFilesToSnapshotTemp()
bool copyFilesToSnapshotTemp (int argc, const char * argv[])
References copyFile(), print(), and verifyFile().
Referenced by addFiles().
copyFilesToTemp()
void copyFilesToTemp (const char ** files, int length)
References copyFile().
Referenced by getShapshot().
copyFilesToWorkspace()
void copyFilesToWorkspace (const char ** files, int length, const char * path)
References copyFile(), and print().
Referenced by getShapshot().
moveFilesTo()
void moveFilesTo (const char * from, const char * to)
References copyFilesTo(), and getFilesInDirectory().
Referenced by moveFilesToTemp().
moveFilesToTemp()
void moveFilesToTemp (const char * from)
References moveFilesTo().