MyVers: src/helpers.c File Reference
helpers.c File Reference
#include "../inc/helpers.h"
#include "../inc/fileHandler.h"
#include "../inc/list.h"
#include <dirent.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>
Macros
#define RED "\x1B[31m"
#define GRN "\x1B[32m"
#define YEL "\x1B[33m"
#define BLU "\x1B[34m"
#define MAG "\x1B[35m"
#define CYN "\x1B[36m"
#define WHT "\x1B[37m"
#define RESET "\x1B[0m"
Functions
void print (char *text, char *color)
void verifyAllocation (void *pointer)
bool verifyFile (const char *fileName)
bool verifyDirectory (const char *folderPath)
bool strIsEqual (const char *str1, const char *str2)
bool verifyVersionadorFolder (void)
bool verifySnapshot (const char *snapshot)
void createFolder (char *folderName, char *newFolderName)
void createLogFolder (const char *folderPath)
void createTxtFile (const char *path, char *fileName, char *text)
void createRepo (const char *folderName)
void createSnapshot (const char *text)
void createContent (const char *path, const char *text)
char generateRandomChar (void)
char * generateHash (int length)
char ** getFilesInDirectory (const char *directoryPath, int *numFiles)
const char * getTxtContentFile (const char *path)
char ** getFoldersInDirectory (const char *directoryPath, int *numFolders)
char * getCurrentDirectory ()
void getShapshot (const char *snapshot)
void getTempFiles (void)
bool addFiles (int argc, const char *argv[])
void printArgv (int argc, const char *argv[])
bool clearFolder (const char *folderPath)
void showLog (void)
void showLogsContent (void)
void showSnapshotContent (const char *snapshotName)
void freeStringArray (char **str, int quantity)
void printTxtFilesContent (const char *directoryPath)
void printTxtContent (FILE *file)
Variables
int errno
Macro Definition Documentation
BLU
#define BLU "\x1B[34m"
CYN
#define CYN "\x1B[36m"
GRN
#define GRN "\x1B[32m"
MAG
#define MAG "\x1B[35m"
RED
#define RED "\x1B[31m"
RESET
#define RESET "\x1B[0m"
WHT
#define WHT "\x1B[37m"
YEL
#define YEL "\x1B[33m"
Function Documentation
addFiles()
bool addFiles (int argc, const char * argv[])
References copyFilesToSnapshotTemp().
Referenced by adiciona().
clearFolder()
bool clearFolder (const char * folderPath)
References strIsEqual().
Referenced by createSnapshot(), getShapshot(), and getTempFiles().
createContent()
void createContent (const char * path, const char * text)
References print().
Referenced by createSnapshot().
createFolder()
void createFolder (char * folderName, char * newFolderName)
Referenced by createLogFolder(), createRepo(), and createSnapshot().
createLogFolder()
void createLogFolder (const char * folderPath)
References addTextInTxtFile(), createFolder(), and createTxtFile().
Referenced by createRepo().
createRepo()
void createRepo (const char * folderName)
References createFolder(), createLogFolder(), and createTxtFile().
Referenced by inciar().
createSnapshot()
void createSnapshot (const char * text)
References addFilesIntoSnapshotFolder(), addSnapshotTempFilesInList(), addSnapshotTextInLog(), cleanList(), clearFolder(), createContent(), createFolder(), createList(), and generateHash().
Referenced by registrar().
createTxtFile()
void createTxtFile (const char * path, char * fileName, char * text)
References print().
Referenced by createLogFolder(), and createRepo().
freeStringArray()
void freeStringArray (char ** str, int quantity)
Referenced by showLogsContent().
generateHash()
char * generateHash (int length)
References generateRandomChar(), and verifyAllocation().
Referenced by createSnapshot().
generateRandomChar()
char generateRandomChar (void)
Referenced by generateHash().
getCurrentDirectory()
char * getCurrentDirectory ()
getFilesInDirectory()
char ** getFilesInDirectory (const char * directoryPath, int * numFiles)
References print().
Referenced by addSnapshotTempFilesInList(), addTempFilesIntoList(), getShapshot(), getTempFiles(), and moveFilesTo().
getFoldersInDirectory()
char ** getFoldersInDirectory (const char * directoryPath, int * numFolders)
References print().
Referenced by showLogsContent().
getShapshot()
void getShapshot (const char * snapshot)
References clearFolder(), copyFilesToTemp(), copyFilesToWorkspace(), and getFilesInDirectory().
Referenced by mudar().
getTempFiles()
void getTempFiles (void)
References addFilesToDir(), addTempFilesIntoList(), cleanList(), clearFolder(), createList(), and getFilesInDirectory().
Referenced by mudar().
getTxtContentFile()
const char * getTxtContentFile (const char * path)
References print(), and verifyFile().
Referenced by showLog(), and showLogsContent().
print()
void print (char * text, char * color)
References BLU, CYN, GRN, MAG, RED, RESET, strIsEqual(), WHT, and YEL.
Referenced by addFilesIntoSnapshotFolder(), addFilesToDir(), addFilesToList(), addTempFilesIntoList(), addTextInTxtFile(), adiciona(), copyFile(), copyFilesToSnapshotTemp(), copyFilesToWorkspace(), createContent(), createTxt(), createTxtFile(), getFilesInDirectory(), getFoldersInDirectory(), getTxtContentFile(), inciar(), mostrar(), mudar(), options(), printArgv(), printTxtContent(), printTxtFilesContent(), registrar(), showLog(), showLogsContent(), showSnapshotContent(), start(), and verifyAllocation().
printArgv()
void printArgv (int argc, const char * argv[])
References print().
Referenced by start().
printTxtContent()
void printTxtContent (FILE * file)
References print().
Referenced by printList().
printTxtFilesContent()
void printTxtFilesContent (const char * directoryPath)
References print().
Referenced by showLogsContent(), and showSnapshotContent().
showLog()
void showLog (void)
References getTxtContentFile(), and print().
Referenced by log().
showLogsContent()
void showLogsContent (void)
References freeStringArray(), getFoldersInDirectory(), getTxtContentFile(), print(), and printTxtFilesContent().
Referenced by log().
showSnapshotContent()
void showSnapshotContent (const char * snapshotName)
References print(), and printTxtFilesContent().
Referenced by mostrar().
strIsEqual()
bool strIsEqual (const char * str1, const char * str2)
Referenced by clearFolder(), log(), mudar(), options(), and print().
verifyAllocation()
void verifyAllocation (void * pointer)
References print(), and RED.
Referenced by generateHash().
verifyDirectory()
bool verifyDirectory (const char * folderPath)
Referenced by addFilesIntoSnapshotFolder(), addFilesToDir(), inciar(), mudar(), registrar(), verifySnapshot(), and verifyVersionadorFolder().
verifyFile()
bool verifyFile (const char * fileName)
Referenced by addTextInTxtFile(), copyFile(), copyFilesToSnapshotTemp(), and getTxtContentFile().
verifySnapshot()
bool verifySnapshot (const char * snapshot)
References verifyDirectory().
Referenced by mudar().
verifyVersionadorFolder()
bool verifyVersionadorFolder (void)
References verifyDirectory().
Referenced by options().
Variable Documentation
errno
int errno extern