MyVers: inc/list.h File Reference
list.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>
#include <stdbool.h>
Typedefs
typedef struct _archive Archive
typedef struct _fileListNode FileListNode
typedef struct _fileList FileList
Functions
FileList * createList (void)
void insertNode (FileList *list, const char *fileName, FILE *file)
void cleanList (FileList *list)
void printList (FileList *list)
void addFilesToList (FileList *list, const char **files, int quantity)
void createFilesInSnapshotFolder (FileList *list, const char *path)
bool isEmpty (FileList *list)
void createTxt (const char *path, FileListNode *node)
Typedef Documentation
Archive
typedef struct _archive Archive
FileList
typedef struct _fileList FileList
FileListNode
typedef struct _fileListNode FileListNode
Function Documentation
addFilesToList()
void addFilesToList (FileList * list, const char ** files, int quantity)
References insertNode(), and print().
Referenced by addSnapshotTempFilesInList(), and addTempFilesIntoList().
cleanList()
void cleanList (FileList * list)
References _archive::file, _fileList::first, _fileListNode::info, _fileList::length, and _fileListNode::next.
Referenced by createSnapshot(), and getTempFiles().
createFilesInSnapshotFolder()
void createFilesInSnapshotFolder (FileList * list, const char * path)
References createTxt(), _fileList::first, and _fileListNode::next.
Referenced by addFilesIntoSnapshotFolder(), and addFilesToDir().
createList()
FileList * createList (void)
References _fileList::first, and _fileList::length.
Referenced by createSnapshot(), and getTempFiles().
createTxt()
void createTxt (const char * path, FileListNode * node)
References _archive::file, _archive::fileName, _fileListNode::info, and print().
Referenced by createFilesInSnapshotFolder().
insertNode()
void insertNode (FileList * list, const char * fileName, FILE * file)
References _archive::file, _archive::fileName, _fileList::first, _fileListNode::info, isEmpty(), _fileList::length, and _fileListNode::next.
Referenced by addFilesToList().
isEmpty()
bool isEmpty (FileList * list)
References _fileList::first.
Referenced by insertNode().
printList()
void printList (FileList * list)
References _archive::file, _archive::fileName, _fileList::first, _fileListNode::info, _fileListNode::next, and printTxtContent().