MyVers: inc/versionador.h File Reference
versionador.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "helpers.h"
Functions
void start (int argc, const char *argv[])
void options (int argc, const char *argv[])
void inciar (void)
void adiciona (int argc, const char *argv[])
void registrar (const char *text)
void log (int argc, const char *argv[])
void mostrar (const char *argv[])
void mudar (const char *argv[])
Function Documentation
adiciona()
void adiciona (int argc, const char * argv[])
References addFiles(), and print().
Referenced by options().
inciar()
void inciar (void)
References createRepo(), print(), and verifyDirectory().
Referenced by options().
log()
void log (int argc, const char * argv[])
References showLog(), showLogsContent(), and strIsEqual().
Referenced by options().
mostrar()
void mostrar (const char * argv[])
References print(), and showSnapshotContent().
Referenced by options().
mudar()
void mudar (const char * argv[])
References getShapshot(), getTempFiles(), print(), strIsEqual(), verifyDirectory(), and verifySnapshot().
Referenced by options().
options()
void options (int argc, const char * argv[])
References adiciona(), inciar(), log(), mostrar(), mudar(), print(), registrar(), strIsEqual(), and verifyVersionadorFolder().
Referenced by start().
registrar()
void registrar (const char * text)
References createSnapshot(), print(), and verifyDirectory().
Referenced by options().
start()
void start (int argc, const char * argv[])
References options(), print(), printArgv(), and test.
Referenced by main().